---
abstract: 'split identifiers into words'
author:
  - 'Nuno Carvalho <smash@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-IdSplitter
requires:
  Data::Dumper: 0
  File::Basename: 0
  File::ShareDir: 0
  Getopt::Long: 0
  LWP::Simple: 0
  String::CamelCase: 0
  Text::Aspell: 0
  strict: 0
  warnings: 0
version: 0.01_1
